# Generated by Django 4.2.1 on 2023-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTb001Plans',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'main_tb001_planes',
                'managed': (True,),
            },
        ),
    ]
