# Generated by Django 4.2.1 on 2023-05-06 15:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTb002Zone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'main_tb002_zonas',
                'managed': (True,),
            },
        ),
        migrations.CreateModel(
            name='MainTb003ZoneHasPlans',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone_id', models.ForeignKey(blank=True, db_column='zone_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.maintb002zone')),
            ],
            options={
                'db_table': 'main_tb003_zona_has_planes',
                'managed': (True,),
            },
        ),
    ]
