# Generated by Django 4.2.1 on 2023-05-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_maintb003zonehasplans_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintb002zone',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
