# Generated by Django 4.2.1 on 2023-05-08 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_maintb002zone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintb003zonehasplans',
            name='plan_id',
            field=models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.maintb001plans'),
        ),
        migrations.AlterField(
            model_name='maintb003zonehasplans',
            name='zone_id',
            field=models.ForeignKey(blank=True, db_column='zone_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.maintb002zone'),
        ),
    ]
